### ISSUE TITLE
Using the application with the triqs version/unstable 

### ISSUE THREAD

**Issue by marcel-klett** [krivenko/som#5]
Dear Dr. Krivenko,

I’m interested in using your SOM library to perform analytic continuation calculations with hdf5 files produced in the triqs/unstable version. Since there is no way to import the hdf5 files produced in the triqs/unstable version to triqs 1.4, i would kinly ask if it is possible to make the SOM library compilable with the triqs/unstable version.

Kind regards,

Marcel Klett

**Comment by krivenko** [comment]
Dear Marcel,

Thank you for your interest in SOM.

> Since there is no way to import the hdf5 files produced in the triqs/unstable version to triqs 1.4

I am somewhat surprised by this statement. I do not remember breaking changes in the HDF5 format between `master` and `unstable` branches of triqs. Could you describe the problem that you faced when tried to import your archives? Maybe there is a problem to be addressed on the library level, which can also be worked around.

>  i would kinly ask if it is possible to make the SOM library compilable with the triqs/unstable version.

Okay, do you really have to use the `unstable` branch of triqs?
The way I understand triqs' development cycle, the `unstable` branch is not meant to be used by anyone except developers themselves.

Currently, I have no intention to port SOM. The reason is simple: `unstable` is... well, too unstable.

Over the course of the last few months, there have been big breaking changes in the library. They have brought along some serious and annoying issues that are still to be fixed (https://github.com/TRIQS/triqs/issues/523 and https://github.com/TRIQS/cpp2py/issues/9, for instance). Porting SOM at this point is going to be a very frustrating experience, I am afraid. Moreover, my personal experience tells me that it is not a very bright idea to try to stick to the `unstable` branch, for it being a moving target. Basically, once you have an application ported, you have to revisit it and commit adjustments every few weeks.

To conclude, I will wait until `unstable` is merged into `master`, and then port SOM.

**Comment by marcel-klett** [comment]
Dear Dr. Krivenko,

Im using your SOM application with the triqs 1.4 version and it is really helpful for me. The reason i have to use the unstable branch of triqs as well, is due to the fact that I'm testing a new solver which is only available with the unstable branch. One of the ideas to check if the new solver works is to compare the analytical continuation of certain solutions.

I found an easy workaround to solve my problem, so i think we can close this issue.

Thank you for your help!

Kind regards,
Marcel Klett

**Comment by krivenko** [comment]
> I found an easy workaround to solve my problem, so i think we can close this issue.

I will keep it open to remind that porting has to be done at some point.

> Thank you for your help!

No problem... Well, I do not think my answer was that helpful after all.

**Comment by krivenko** [comment]
Dear Marcel,

I know it has been a very long time since you opened this issue, but it is better late than never.
The [2.0.0 release](https://github.com/krivenko/som/releases/tag/2.0.0) of SOM is finally here. It is compatible with Python 3 and the most recent stable version of TRIQS, 3.1.x. Altough it is still not the bleeding edge `unstable` branch of TRIQS, it is much better in terms of compatibility than the long outdated 1.4.

In case you are still interested in using SOM, you might want to try some of the [new features](https://krivenko.github.io/som/ChangeLog.html#major-changes-and-new-features) coming with 2.0.0.

Best regards,
Dr. Igor Krivenko
